sudo: required

services:
  - docker

env:
  global:
    - VAULT_VERSION=${VAULT_VERSION:-0.11.4}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build docker image
      script:
        - make
    - stage: test images
      script:
        - make compose-file
        - docker-compose up --build -d
        - sleep 10s
        - make test
        - docker-compose kill
        - docker-compose down
    - stage: upload
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker tag  ${USER}/vault:latest ${DOCKER_USERNAME}/docker-vault:latest
        - docker push ${DOCKER_USERNAME}/docker-vault:latest
        #
        - docker tag  ${DOCKER_USERNAME}/docker-vault:latest ${DOCKER_USERNAME}/docker-vault:${BUILD_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-vault:${BUILD_VERSION}
        - docker logout
