---
version: '3.3'

services:

  consul2:
    image: bodsch/docker-consul
    container_name: consul2
    hostname: consul2
    ports:
      - 8400
      - 8500
      - 8600
    links:
      - consul-master:consul-master
    command: 'agent -data-dir /data -server -join consul-master'
    networks:
      consul:
        ipv4_address: 192.168.10.20
