---
version: '3.3'

services:

  vault:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE
        - BUILD_DATE
        - BUILD_VERSION
        - VAULT_VERSION
    restart: always
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    links:
      - consul-master
    depends_on:
      - consul-master
    volumes:
      - ./config/vault.conf:/config/vault.conf
    command: "server -config=/config/vault.conf -log-level=debug"
    networks:
      consul:
        ipv4_address: 192.168.10.30
