---
version: '3.3'

services:

  vault:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_IMAGE=${BUILD_IMAGE}
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
        - VAULT_VERSION=${VAULT_VERSION}
    restart: always
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    links:
      - consul-master:consul
    depends_on:
      - consul-master
    volumes:
      - ./config/vault.conf:/config/vault.conf
    command: "server -config=/config/vault.conf"
    networks:
      consul:
        ipv4_address: 192.168.10.30
